version: "3.8"

services:
  dal-tokki-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: dal-tokki-api:v1.0
    container_name: dal-tokki-api
    ports:
      - "80:8000"
    volumes:
      - ./data:/app/app/data
      - .env:/app/.env:ro  # .env 파일을 마운트 (예: 로컬 env 디렉터리 사용)
    deploy:
      replicas: ${REPLICAS:-1}
      restart_policy:
        condition: on-failure

